---
title: "Évènements indésirables en urologie"
author: "Philippe MICHEL"
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    theme: caiman
    highlight: github
    toc: yes
  tufte::tufte_html: default
  word_document:
    toc: yes
  html_document:
    self_contained: true
    df_print: paged
    toc: yes
    toc_float: 
       collapsed: false
    theme: lumen
  html_notebook:
    fig_caption: yes
    theme: spacelab
  pdf_document:
    includes:
      in_header: tete.tex
    keep_tex: yes
    latex_engine: lualatex
    toc: yes
editor_options:
  chunk_output_type: console
---

```{r setup, include= FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
# knitr::opts_chunk$set(echo = TRUE, warning = TRUE, message = TRUE)
```


```{r info}
rm(list=ls())
library("thesisph")
library("missMDA")
library("epiDisplay")
library("factoextra")
library("lubridate")
library("knitr")
library("stringr")
library("tidyverse")
library("kableExtra")
library("pyramid")
# sessionInfo()
```

```{r import}
tt <- read.csv("data/REX2.csv", header= TRUE, row.names = 1, na.strings = c(""))
#summary(tt)
```
# Description

## Les patients

L'échantillon comporte `r dim(tt)[1]` cas. On a retenu `r dim(tt)[2]` variables utiles & utilisables.

```{r pyr}
lage <- seq(0,100,10)

lima <- c("0-10","11-20","21-30" ,"31-40","41-50","51-60","61-70","71-80","81-90", "> 90")

mm <- subset(tt, Sexe =="masculin")
zzm <- as.numeric(table(cut(mm$Age,lage)))
ff <- subset(tt, Sexe =="féminin")
zzf <- as.numeric(table(cut(ff$Age,lage)))
age <- data.frame(zzm,zzf, lima)
pyramid(age, Llab = "masculin", Rlab = "féminin", Clab = "Âge", Cadj = 0.01, GL = TRUE, main = "Pyramide des âges")
```

```{r cim}
zz <- table(tt$Libelle.CIM10)
zz <- sort(zz, decreasing = TRUE)[1:12]
kable(zz, col.names = c("", "n"), caption = "Libellés CIM10 les plus fréquents", label = "cim")
```

